#!/bin/bash

#set -x

PACKAGE=vdr-plugin-skindesigner
DISTRIBUTION=trusty
BUILDPREFIX=yavdr
PPA=yavdr/unstable-vdr

UPSTREAMURL=git://projects.vdr-developer.org/vdr-plugin-skindesigner.git
PACKAGEURL=git@github.com:yavdr/${PACKAGE}.git

# prepare:
# git clone -o origin ${PACKAGEURL} ${PACKAGE}
# cd ${PACKAGE}
# git remote add upstream ${UPSTREAMURL}

# get upstream changes
git fetch upstream

# get debian changes
git pull origin

PKGVERSION=`dpkg-parsechangelog | sed -n 's/^Version: \(.*\)-.*/\1/p'`
UPSTREAMVERSION=`git describe upstream/master`

if dpkg --compare-versions ${PKGVERSION} lt ${UPSTREAMVERSION}
then
  NEWVERSION=${UPSTREAMVERSION}-0${BUILDPREFIX}0~${DISTRIBUTION}
  CHANGES=`git log --reverse --pretty="format:%h: %s" HEAD..upstream/master upstream/master`

  git merge --commit --log -m "Merge branch 'upstream/master'" upstream/master
  git archive --format=tar.gz --prefix=${PACKAGE}-${UPSTREAMVERSION}/ --output=../${PACKAGE}_${UPSTREAMVERSION}.orig.tar.gz upstream/master
  dch -v ${NEWVERSION} -u medium -D ${DISTRIBUTION} --force-distribution "new upstream snapshot"
  while read -r line ; do dch -a "${line}" ; done <<< "${CHANGES}"
  git add debian/changelog
  git commit -m "new upstream snapshot"
  git push
  git push --tags
  debuild -S -sa
  dput -U ppa:${PPA} ../${PACKAGE}_${NEWVERSION}_source.changes

  # upload to testing/precise
  OTHERDISTRIBUTION=precise
  OTHERPPA=yavdr/testing-vdr
  OTHERVERSION=${UPSTREAMVERSION}-0${BUILDPREFIX}0~${OTHERDISTRIBUTION}
  dch -v ${OTHERVERSION} --force-bad-version -u medium -D ${OTHERDISTRIBUTION} --force-distribution "rebuild for ${OTHERDISTRIBUTION}"
  debuild -S -sa
  dput -U ppa:${OTHERPPA} ../${PACKAGE}_${OTHERVERSION}_source.changes
  git checkout -- debian/changelog
fi
