#!/bin/bash

#set -x

PACKAGE=vdr-plugin-skindesigner
DISTRIBUTION=precise
BUILDPREFIX=yavdr
PPA=yavdr/testing-vdr

UPSTREAMURL=git://projects.vdr-developer.org/vdr-plugin-skindesigner.git
PACKAGEURL=git@github.com:yavdr/${PACKAGE}.git

# prepare:
# git clone -o origin ${PACKAGEURL} ${PACKAGE}
# cd ${PACKAGE}
# git checkout testing-0.5
# git remote add upstream ${UPSTREAMURL}

# get upstream changes
git fetch upstream

# get debian changes
git pull origin

PKGVERSION=`dpkg-parsechangelog | sed -n 's/^Version: \(.*\)-.*/\1/p'`
UPSTREAMVERSION=`git describe upstream/master`

if dpkg --compare-versions ${PKGVERSION} lt ${UPSTREAMVERSION}
then
  NEWVERSION=${UPSTREAMVERSION}-0${BUILDPREFIX}0~${DISTRIBUTION}
  CHANGES=`git log --reverse --pretty="format:%h: %s" HEAD..upstream/master upstream/master`

  git merge --commit --log -m "Merge branch 'upstream/master'" upstream/master
  if [ ! -e ../${PACKAGE}_${UPSTREAMVERSION}.orig.tar.gz ]
  then
    git archive --format=tar.gz --prefix=${PACKAGE}-${UPSTREAMVERSION}/ --output=../${PACKAGE}_${UPSTREAMVERSION}.orig.tar.gz upstream/master
  fi
  dch -v ${NEWVERSION} -u medium -D ${DISTRIBUTION} --force-distribution "new upstream snapshot"
  while read -r line ; do dch -a "${line}" ; done <<< "${CHANGES}"
  if [ -z "$DRYRUN" ]
  then
    git add debian/changelog
    git commit -m "new upstream snapshot"
    git push
    git push --tags
    debuild -S -sa
    dput -U ppa:${PPA} ../${PACKAGE}_${NEWVERSION}_source.changes
  fi
fi
